spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.114.118:3306/boke?useSSL=false&serverTimezone=UTC
    username: root
    password: suifeng1234
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: mediaType
    converters:
      preferred-json-mapper: jackson

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.entity

jwt:
  secretKey: suifeng
  ttl: 1800000

logging:
  level:
    root: info
    com.blog: info
